In [1]:
import numpy as np

In [2]:
data = np.load('../../data/pseudo/preprocess/o_n_-_-.npy')
data.shape

(122, 483333)

In [3]:
data_sub = data[:2, :6]
data_sub

array([[1, 3, 4, 1, 4, 3],
       [1, 3, 4, 1, 4, 3]])

In [4]:
data_ravel = data_sub.ravel()
n = data_ravel.shape[0]
encode = np.zeros((n, 5))
encode[np.arange(n), data_ravel] = 1
encode.reshape(data_sub.shape+(5,))

array([[[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]]])

In [5]:
from keras.utils.np_utils import to_categorical   

Using TensorFlow backend.


In [6]:
categorical_labels = to_categorical(data_sub, num_classes=5)

In [7]:
categorical_labels

array([[[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]]], dtype=float32)

In [8]:
from tensorly.decomposition import robust_pca

In [9]:
D, E = robust_pca(categorical_labels)


Converged in 95 iterations


In [11]:
D

array([[[-1.110223e-16,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00]],

       [[-1.110223e-16,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
          0.000000e+00],
        [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.0

In [14]:
np.abs(np.floor(E))

array([[[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]],

       [[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.]]], dtype=float32)