In [4]:
from Bio.Cluster import distancematrix

In [5]:
import numpy as np

In [8]:
data = np.array([[0, 1,  2,  3],
                 [4, 5,  6,  7],
                 [8, 9, 10, 11],
                 [1, 2,  3,  4]])
distancematrix(data)

[array([], dtype=float64),
 array([16.]),
 array([64., 16.]),
 array([ 1.,  9., 49.])]

In [18]:
data = np.array([[0, 0],
                 [3, 4],
                 [5, 6],
                 [1, 2]])
distancematrix(data, transpose=False, dist='e')

[array([], dtype=float64),
 array([12.5]),
 array([30.5,  4. ]),
 array([ 2.5,  4. , 16. ])]

In [13]:
np.array([[ 0., 16., 64., 1.], [16., 0., 16., 9.], [64., 16., 0., 49.], [ 1., 9., 49., 0.]])

array([[ 0., 16., 64.,  1.],
       [16.,  0., 16.,  9.],
       [64., 16.,  0., 49.],
       [ 1.,  9., 49.,  0.]])